### ISSUE TITLE
Initialize apt sources

### ISSUE THREAD

**Issue by ryanpdx** [oresat/oresat-linux-updater#3]
Need to setup the update maker to initialize the local apt `source.list` file as python3-apt will leave that file blank on first time setup.

Probably can just copy the context of the real root apt `source.list` file into the local one.

Also need to append `deb [trusted=yes] https://debian.oresat.org/packages ./` so the update maker has access to OreSat Debain apt repo.

**Comment by ryanpdx** [comment]
Also need to copy the apt repo signatures (files in `/var/lib/apt/lists/`)

**Comment by mairacanal** [comment]
By "copy the context of the real root apt `source.list` file into the local one", do you mean just copy the original `source.list` for Debian? I mean just setting up the code below.

```
deb http://deb.debian.org/debian buster main contrib non-free
deb-src http://deb.debian.org/debian buster main contrib non-free

deb http://deb.debian.org/debian-security/ buster/updates main contrib non-free
deb-src http://deb.debian.org/debian-security/ buster/updates main contrib non-free

deb http://deb.debian.org/debian buster-updates main contrib non-free
deb-src http://deb.debian.org/debian buster-updates main contrib non-free
```

**Comment by ryanpdx** [comment]
Basically yes, just copy the content of `/etc/apt/sources.list`. The specific contents of that file can differ between versions of Debian / architecture.

**Comment by mairacanal** [comment]
Ah ok, I will try to tackle this issue.
